name: Documentation build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev, fury]'
    - name: Build docs
      run: |
        cd doc
        make html
    - name: Understand the file-system structure 1
      run: |
        ls /home/runner/work/cloudknot/

    - name: Understand the file-system structure 2
      run: |
        ls /home/runner/work/cloudknot/cloudknot/doc/

    - name: Understand the file-system structure 3
      run: |
        ls /home/runner/work/cloudknot/cloudknot/doc/_build
